Exercise 2 Commit
konradkaniewskiey/java-bootcamp pull request #2
Opened 2023-03-01 12:22 UTC by konradkaniewskiey

2023-03-01 16:02 UTC, jaroslawwoloch requested changes

2023-03-01 16:02 UTC, jaroslawwoloch commented on src/DecileCounter.java
> +    public static void Decile() {
why static?

2023-03-01 16:02 UTC, jaroslawwoloch commented on src/DecileCounter.java
> +            System.out.print("Enter a number from 1 to 1000 (or 'END' to stop): ");
.... enter a number and hit RETURN ...... - it's needed to finish line and trigger scaner

2023-03-01 16:02 UTC, jaroslawwoloch commented on src/DecileCounter.java
> +                    System.out.println("Invalid input. Number must be between 1 and 1000.");
on this sytuation You have message :Enter...... then number provided by user and error in this same line - put error message into new line

2023-03-01 16:02 UTC, jaroslawwoloch commented on src/DecileCounter.java
> +        for (int i = 0; i < size; i++) {
this don't meet business requirements. Read what is decile https://en.wikipedia.org/wiki/Decile and set for all population (1-1000)

2023-03-02 08:30 UTC, konradkaniewskiey commented on src/DecileCounter.java
> +                    System.out.println("Invalid input. Number must be between 1 and 1000.");
![image](https://user-images.githubusercontent.com/105655286/222373758-68805487-c426-4baf-a84a-9814dbd191ba.png)

Not sure what you mean, looks fine to me.

2023-03-02 09:36 UTC, jaroslawwoloch commented on src/DecileCounter.java
> +                    System.out.println("Invalid input. Number must be between 1 and 1000.");
ok Scanner.nextLine after read move cursor to next line but other scanner.next... methods don't do that.

2023-04-04 10:52 UTC, merged